### ISSUE TITLE
Returned body is null

### ISSUE THREAD

**Issue by rafaellobomeetime** [digineo/sisimai-web#47]
Hi there, I was trying to work with this docker container but when I send a request through postman, I get a null return with status code 200.

Postman request:
![image](https://github.com/digineo/sisimai-web/assets/141650882/66f4ae40-06a4-472d-a826-4911587f8bf4)

Docker logs:
![image](https://github.com/digineo/sisimai-web/assets/141650882/8862b457-5beb-4035-8b9b-2513cae8ab58)

Docker container:
![image](https://github.com/digineo/sisimai-web/assets/141650882/76d6c577-adb2-4189-a93e-0860f1be1392)

Docker command: docker run -d -p 3000:3000 ghcr.io/digineo/sisimai-web

Could you guys point out what am I doing wrong?

**Comment by dmke** [comment]
I'll have a look tomorrow, when I'm back in office. So far, everything looks alright.

It could be an issue with you mail. Does it really only have 5 lines? It could very well be, that Sisimai doesn't recognize it.

**Comment by dmke** [comment]
The response is actually `null`, if Sisimai doesn't detect any bounce information.

Looking at the mail, it looks suspiciously like the example from the README. However, the README only shows the first 5 lines (`head -5`) of a local file (`message.eml`). You do need to send the full email contents to the HTTP endpoint for this to work.

You can find a few examples in the [spec/fixtures/messages/](https://github.com/digineo/sisimai-web/tree/master/spec/fixtures/messages) directory.
